### ISSUE TITLE
Integer Conversion BIFs

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#143]
- [x] `integer_to_binary/1` (#313)
- [x] `integer_to_binary/2` (#314)
- [x] `integer_to_list/1` (#315)
- [x] `integer_to_list/2` (#316)
- [x] `list_to_integer/1` (#317)
- [x] `list_to_integer/2` (#318)
