### ISSUE TITLE
Float Conversion BIFs

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#176]
`float_to_binary` and/or `float_to_list` may be used for printing.  `list_to_float` could be used for parsing strings.

- [x] `float_to_binary/1` (#321)
- [x] `float_to_binary/2` (#322)
- [x] `float_to_list/1` (#323)
- [x] `float_to_list/2` (#324)
- [x] `list_to_float/1` (#325)
