### ISSUE TITLE
Process Spawning BIFs

### ISSUE THREAD

**Issue by KronicDeth** [lumen/lumen#210]
The remaining, local, unimplemented `spawn_*` BIFs

- [x] [`spawn(function)`](http://erlang.org/doc/man/erlang.html#spawn-1) (#332)
- [x] [`spawn_link(function)`](http://erlang.org/doc/man/erlang.html#spawn_link-1) (#337)
- [x] [`spawn_monitor(function)`](http://erlang.org/doc/man/erlang.html#spawn_monitor-1) (#338)
- [x] [`spawn_monitor(module function, arguments)`](http://erlang.org/doc/man/erlang.html#spawn_monitor-3) (#341)
- [x] [`spawn_opt(function, options)`](http://erlang.org/doc/man/erlang.html#spawn_opt-2) (#340)
- [x] [`spawn_opt(module function, args, options)`](http://erlang.org/doc/man/erlang.html#spawn_opt-4) (#230)
